version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: someone-help-api
    image: someone-help-api:latest
    ports:
      - "5014:5014"
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: someone-help-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: someone-help
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
